---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: always
  image: ansible/ansible:ubuntu1404
  commands:
  - ansible --version
  - ansible-lint tasks/setup.yml
