---
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ drone_dir }}"
  tags:
    - drone-server

- name: run drone server
  docker_container:
    name: drone-server
    image: "drone/drone:{{ drone_version }}"
    state: started
    restart_policy: always
    ports:
      - "{{ drone_host_port }}:80"
    volumes:
      - "{{ drone_dir }}:/data"
    env:
      DRONE_SERVER_HOST: "{{ drone_server_host }}"
      DRONE_SERVER_PROTO: "{{ drone_server_proto }}"
      DRONE_TLS_AUTOCERT: "false"
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_AGENTS_ENABLED: "true"
      DRONE_GITHUB_SERVER: "https://github.com"
      DRONE_GITHUB_CLIENT_ID: "{{ drone_github_client_id }}"
      DRONE_GITHUB_CLIENT_SECRET: "{{ drone_github_client_secret }}"
      DRONE_LOGS_PRETTY: "{{ drone_logs_pretty }}"
      DRONE_LOGS_COLOR: "{{ drone_logs_color }}"
  tags:
    - drone-server
